### ISSUE TITLE
create unique puzzle ID in the output

### ISSUE THREAD

**Issue by yegor256** [teamed/pdd#31]
Let's generate unique puzzle ID in XML output

**Comment by davvd** [comment]
@yegor256 right, I added the `bug` tag

**Comment by davvd** [comment]
I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-70d5393a

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.2`
