### ISSUE TITLE
pdd should log files being processed

### ISSUE THREAD

**Issue by dispmaxstaff** [teamed/pdd#36]
Else it's impossible to determine which file pdd fails at, we excluded all possible binary files but still a failure, this is the log snippet:

	+ pdd --file=/dev/null
	INFO: "my version is 0.14"
	INFO: "reading ."
	INFO: "excluding **/*.exe"
	INFO: "excluding **/*.dll"
	INFO: "excluding **/*.ico"
	INFO: "44 file(s) found"
	/var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd/source.rb:43:in `match': invalid byte sequence in UTF-8 (ArgumentError)
		from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd/source.rb:43:in `block in puzzles'
		from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd/source.rb:42:in `each'
		from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd/source.rb:42:in `each_with_index'
		from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd/source.rb:42:in `puzzles'
		from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd/source.rb:134:in `puzzles'
		from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd.rb:96:in `block (3 levels) in xml'
		from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd.rb:95:in `each'
		from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd.rb:95:in `block (2 levels) in xml'
		from /var/lib/gems/1.9.1/gems/nokogiri-1.6.5/lib/nokogiri/xml/builder.rb:391:in `call'
		from /var/lib/gems/1.9.1/gems/nokogiri-1.6.5/lib/nokogiri/xml/builder.rb:391:in `insert'
		from /var/lib/gems/1.9.1/gems/nokogiri-1.6.5/lib/nokogiri/xml/builder.rb:375:in `method_missing'
		from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd.rb:94:in `block in xml'
		from /var/lib/gems/1.9.1/gems/nokogiri-1.6.5/lib/nokogiri/xml/builder.rb:293:in `initialize'
		from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd.rb:92:in `new'
		from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd.rb:92:in `xml'
		from /var/lib/gems/1.9.1/gems/pdd-0.14/bin/pdd:90:in `<top (required)>'
		from /usr/local/bin/pdd:23:in `load'
		from /usr/local/bin/pdd:23:in `<main>'

**Comment by davvd** [comment]
@yegor256 this is yours, pls go ahead

**Comment by davvd** [comment]
@dispmaxstaff thanks a lot for reporting, **15 mins** added to your acc, pmt ID `54546201`

**Comment by yegor256** [comment]
@dispmaxstaff this is fixed in version 0.14.1, please check

**Comment by dispmaxstaff** [comment]
@yegor256 this works, closing

**Comment by davvd** [comment]
@yegor256 I added **38 mins** to your account, many thanks for working with the project! The completion time here was 000-fd6462b5.... the bonus for fast delivery (age=3458)... +38 added to your rating, at the moment it is: [+9123](http://www.netbout.com/b/35008?open=rating)
