### ISSUE TITLE
Include a link to the parent issue in puzzles on Github

### ISSUE THREAD

**Issue by Suseika** [teamed/pdd#41]
Consider jcabi/jcabi-dynamo#35. It would be great to have a link to the parent issue in the issue description. The parent issue for that puzzle would be jcabi/jcabi-dynamo#8, but you can't tell that without looking into source code. If we have to provide the parent issue when creating a todo, why not show it in the puzzle description?

**Comment by davvd** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@Suseika what if it's not a Github project? How can we build a URL of that issue when we're looking at Git repository?

**Comment by Suseika** [comment]
@yegor256 We don't need to build an URL, we send Github-flavored markdown to Github. We just write #number_of_issue, and it gets transformed to an url by Github, right? PDD syntax already requires the number of issue anyway. It won't hurt just adding that number somewhere in the description, if it is present.

**Comment by yegor256** [comment]
@Suseika what if the user is using JIRA? or Trac? we have to be tracker-agnostic... see the problem?

**Comment by Suseika** [comment]
@yegor256 I probably posted this issue in a wrong repository. Dmarkov didn't type the top message in jcabi/jcabi-dynamo#35 manually, it is generated from `pdd` output, right? The software used to generate the issue text would benefit from a github-specific formatting option that allows inserting the link to a parent Github issue.

**Comment by yegor256** [comment]
@Suseika yes, I'll take this into account. At the moment, this information is available in XML output of pdd, in `/puzzle/ticket` node.
