### ISSUE TITLE
pdd should detect @todo without issue number

### ISSUE THREAD

**Issue by krzyk** [teamed/pdd#42]
right now pdd will ignore `@todo` which has only description, e.g.:
```
        /**
         * Who knows.
         * @todo Since we are a relay, it seems that we should not be using
         *  this State class, but rather return the error that XJM returns,
         *  so that the client knows what to do with it, i.e. we should just use
         *  HttpURLConnection, and handle/intercept the messages we care about
         *  and relay the rest.
         */
```

The above todo will be ignored, but an error should be displayed that it is not in the correct format.

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.15`

**Comment by davvd** [comment]
@krzyk thank you for the ticket reported, I topped your account for 15 mins, transaction `64884078`

**Comment by yegor256** [comment]
@krzyk I believe the problem is solved

**Comment by krzyk** [comment]
@yegor256 thanks
