### ISSUE TITLE
pdd deployment on travis-ci fails

### ISSUE THREAD

**Issue by K-ballo** [teamed/pdd#44]
The following snippet used to work fine to deploy _pdd_ on _travis-ci_:

    - set -e
    - travis_retry sudo apt-get install -y --fix-missing libmagic1 libmagic-dev
    - gem install --no-ri pdd

But this last step suddenly started failing, with the following output:

    Fetching: rake-10.4.2.gem (100%)
    Successfully installed rake-10.4.2
    Fetching: slop-3.6.0.gem (100%)
    Successfully installed slop-3.6.0
    Fetching: ruby-filemagic-0.6.1.gem (100%)
    Building native extensions.  This could take a while...
    ruby-filemagic-0.6.1 [2014-08-19]:
    * Account for options passed to FileMagic.fm (issue #7 reported by Adam
      Wróbel).
    Successfully installed ruby-filemagic-0.6.1
    Fetching: mini_portile-0.6.2.gem (100%)
    Successfully installed mini_portile-0.6.2
    Fetching: nokogiri-1.6.5.gem (100%)
    Building native extensions.  This could take a while...
    ERROR:  Error installing pdd:
    	ERROR: Failed to build gem native extension.

See [here](https://travis-ci.org/K-ballo/travis-cpp/jobs/79305289) for the full log.

**Comment by yegor256** [comment]
@K-ballo can you please try this instead:

```yaml
addons:
  apt:
    packages:
      - libmagic1
      - libmagic-dev
script:
  - set -e
  - gem install --no-ri --no-rdoc pdd
```

**Comment by K-ballo** [comment]
@yegor256 that causes it to fail earlier, full log [here](https://travis-ci.org/K-ballo/travis-cpp/jobs/80042617#L115).

**Comment by yegor256** [comment]
@K-ballo looks like `addons/apt/packages` are installed **after** `install`. That's why, please try to put this line into `script` section:

```
gem install --no-ri --no-rdoc pdd
```

**Comment by K-ballo** [comment]
@yegor256 That makes no sense, why would I perform the install stage after `install`?

Moved to the `script` section, same output except now it shows as a build failure rather than an configuration failure. Full log [here](https://travis-ci.org/K-ballo/travis-cpp/jobs/80095186#L117).

**Comment by yegor256** [comment]
@K-ballo do you see in [this log](https://travis-ci.org/K-ballo/travis-cpp/jobs/80095186) where apt-get packages are installed? I don't...

**Comment by K-ballo** [comment]
> @K-ballo do you see in this log where apt-get packages are installed? I don't...

I do not.

**Comment by K-ballo** [comment]
@yegor256 After further inspection, this appears to be an issue on travis side, no longer supporting the `packages` add-on on legacy infrastructure.

**Comment by yegor256** [comment]
@K-ballo there you go... let's close the ticket?
