### ISSUE TITLE
No tests and documentation about excluding multiple files/paths

### ISSUE THREAD

**Issue by mkordas** [teamed/pdd#50]
When looking at [search results](https://github.com/teamed/pdd/search?utf8=%E2%9C%93&q=exclude) for exclude feature, I see it supports multiple arguments, but there's neither test nor documentation to show how to use multiple excludes. 

I'd expect test with at least two excludes and documentation with example for that feature.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@mkordas what about this: https://github.com/teamed/pdd/blob/7d979eb1f26ed66cdfaa28a5e1346295ecb2901c/features/cli.feature#L54 there are two `excludes`

**Comment by yegor256** [comment]
@mkordas extra doc: 0a622db

**Comment by mkordas** [comment]
@yegor256 What about multiple paths provided to one exclude? Is the following
```
pdd --exclude=**/*.java,**/*.groovy
```
 valid or should I write
```
pdd --exclude=**/*.java, **/*.groovy
```
or maybe some quotes are needed? From docs it's not clear, I don't see tests for it either.

**Comment by yegor256** [comment]
@mkordas maybe that will work, but I'm not sure. just use multiple `--execute` and you'll be fine

**Comment by mkordas** [comment]
@yegor256 the thing here is that it works and is used in projects, so the question is if we want to have undocumented feature without tests: https://github.com/teamed/qulice/blob/fe57956fef458ad89afbe379afa217c9863aceb7/.travis.yml#L25
