### ISSUE TITLE
How PUZZLES.md gets updated?

### ISSUE THREAD

**Issue by NikolaDespotoski** [teamed/pdd#52]
I have a question regarding how the the PUZZLES.md gets populated if the `pdd` find files that have puzzles? In other teamed.io projects I saw that in commit history PUZZLES.md is updated by a contributor. 

If the `pdd` is executed by `rultor`, will rultor update the PUZZLES.md file? 
When `pdd` is used in project, does each contributor should execute the `pdd` locally and update the the puzzles.md file manually/by appending his puzzles and then commit it?

**Comment by yegor256** [comment]
@NikolaDespotoski this tool is producing `puzzles.xml` file, which then can be converted to whatever you need, but specifically in your project. The `pdd` tool itself doesn't know anything about your specific project details and your tickets. It's all done by other (proprietary) tools.
